### ISSUE TITLE
How to install and use?

### ISSUE THREAD

**Issue by DimitriPapadopoulos** [CenterForOpenScience/osf-sync#196]
Trying to mass upload files to OSF. Any chance I can use this piece of software? How to install?

**Comment by saradbowman** [comment]
Hi @DimitriPapadopoulos, unfortunately, this project isn't being maintained. You might try:
https://github.com/osfclient/osfclient
or
https://github.com/CenterForOpenScience/osfr

**Comment by DimitriPapadopoulos** [comment]
Indeed `osf` works just fine - and it's easier to call from a script.
